export default {
  ADDED_A_COMMENT: "Added a comment",
  ADDED_A_FACT: "Added a fact",
  AGREED_ON_SPECIES_NAME: "Agreed on species name",
  CUSTOM_FIELD_EDITED: "Custom field edited",
  DOCUMENT_CREATED: "Document Created",
  DOCUMENT_TAG_UPDATED: "Document tag updated",
  DOCUMENT_UPDATED: "Document Updated",
  FEATURED: "Featured",
  FLAG_REMOVED: "Flag removed",
  FLAGGED: "Flagged",
  OBSERVATION_CREATED: "Observation created",
  OBSERVATION_SPECIES_GROUP_UPDATED: "Observation species group updated",
  OBSERVATION_TAG_UPDATED: "Observation tag updated",
  OBSERVATION_UPDATED: "Observation updated",
  OBV_LOCKED: "obv locked",
  OBV_UNLOCKED: "obv unlocked",
  POSTED_RESOURCE: "Posted resource",
  RATED_MEDIA_RESOURCE: "Rated media resource",
  REMOVED_RESORUCE: "Removed resoruce",
  SUGGESTED_SPECIES_NAME: "Suggested species name",
  SUGGESTION_REMOVED: "Suggestion removed",
  UNFEATURED: "UnFeatured",
  UNFLAGGED: "unflagged",
  UPDATED_FACT: "Updated fact"
};
