export default {
  ADDED_A_COMMENT: "Added a comment",
  ADDED_A_FACT: "Added a fact",
  ADDED_COMMON_NAME: "Added common name",
  ADDED_SPECIES_FIELD: "Added species field",
  ADDED_SYNONYM: "Added synonym",
  AGREED_ON_SPECIES_NAME: "Agreed on species name",
  CREATED_SPECIES: "Created species",
  CUSTOM_FIELD_EDITED: "Custom field edited",
  DELETED_COMMON_NAME: "Deleted common name",
  DELETED_SPECIES_FIELD: "Deleted species field",
  DELETED_SYNONYM: "Deleted synonym",
  DOCUMENT_CREATED: "Document Created",
  DOCUMENT_TAG_UPDATED: "Document tag updated",
  DOCUMENT_UPDATED: "Document Updated",
  FEATURED: "Featured",
  FLAG_REMOVED: "Flag removed",
  FLAGGED: "Flagged",
  OBSERVATION_CREATED: "Observation created",
  OBSERVATION_SPECIES_GROUP_UPDATED: "Observation species group updated",
  OBSERVATION_TAG_UPDATED: "Observation tag updated",
  OBSERVATION_UPDATED: "Observation updated",
  OBV_LOCKED: "obv locked",
  OBV_UNLOCKED: "obv unlocked",
  POSTED_RESOURCE: "Posted resource",
  RATED_MEDIA_RESOURCE: "Rated media resource",
  REMOVED_RESORUCE: "Removed resoruce",
  SUGGESTED_SPECIES_NAME: "Suggested species name",
  SUGGESTION_REMOVED: "Suggestion removed",
  TAXON_NAME_UPDATED: "Taxon name updated",
  UNFEATURED: "UnFeatured",
  UNFLAGGED: "unflagged",
  UPDATED_COMMON_NAME: "Updated common name",
  UPDATED_FACT: "Updated fact",
  UPDATED_SYNONYM: "Updated synonym",
  PAGE_UPDATED: "Page updated",
  UPDATE_TAXON_ID: "Updated taxon id"
};
